Bump Rust toolchain to 1.89
To address CI issue:

error: failed to compile `cargo-edit v0.13.8`, intermediate artifacts can be found at `/tmp/cargo-installQhzFcm`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.88.0 is not supported by the following package:
    smol_str@0.3.4 requires rustc 1.89